In [1]:
import pandas as pd
import numpy as np

In [2]:
patient=pd.read_excel('input_diabetes.xlsx')

In [3]:
patient.head()

glucose  bp  skin  insulin   bmi  pedigree  age  diabetes
0      148  72    35        0  33.6     0.627   50         1
1       85  66    29        0  26.6     0.351   31         0
2      183  64     0        0  23.3     0.672   32         1
3       89  66    23       94  28.1     0.167   21         0
4      137  40    35      168  43.1     2.288   33         1

In [4]:
patient.shape

(768, 8)

In [5]:
patient.describe()

glucose          bp        skin     insulin         bmi    pedigree  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   
mean   120.894531   69.105469   20.536458   79.799479   31.992578    0.471876   
std     31.972618   19.355807   15.952218  115.244002    7.884160    0.331329   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.078000   
25%     99.000000   62.000000    0.000000    0.000000   27.300000    0.243750   
50%    117.000000   72.000000   23.000000   30.500000   32.000000    0.372500   
75%    140.250000   80.000000   32.000000  127.250000   36.600000    0.626250   
max    199.000000  122.000000   99.000000  846.000000   67.100000    2.420000   

              age    diabetes  
count  768.000000  768.000000  
mean    33.240885    0.348958  
std     11.760232    0.476951  
min     21.000000    0.000000  
25%     24.000000    0.000000  
50%     29.000000    0.000000  
75%     41.000000    1.000000  
max     81.000000    1.000000

In [6]:
patient.isnull().sum()

glucose     0
bp          0
skin        0
insulin     0
bmi         0
pedigree    0
age         0
diabetes    0
dtype: int64

In [7]:
x=patient.drop(['diabetes'], axis=1)
y=patient['diabetes']

In [8]:
x.head()

glucose  bp  skin  insulin   bmi  pedigree  age
0      148  72    35        0  33.6     0.627   50
1       85  66    29        0  26.6     0.351   31
2      183  64     0        0  23.3     0.672   32
3       89  66    23       94  28.1     0.167   21
4      137  40    35      168  43.1     2.288   33

# Train_Test split method

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [11]:
x_train.head()

glucose  bp  skin  insulin   bmi  pedigree  age
78       131   0     0        0  43.2     0.270   26
222      119   0     0        0  25.2     0.209   37
31       158  76    36      245  31.6     0.851   28
198      109  64    44       99  34.8     0.905   26
754      154  78    32        0  32.4     0.443   45

In [12]:
y_train.head()

78     1
222    0
31     1
198    1
754    1
Name: diabetes, dtype: int64

# Build Default Model(IIFPA)

In [13]:
from sklearn.tree import DecisionTreeClassifier 

In [14]:
DTC=DecisionTreeClassifier() 

In [15]:
DTC.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [16]:
y_test_pred=DTC.predict(x_test) #predicting the model on test data

In [17]:
y_test_pred

array([0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1])

In [18]:
comp_df=pd.DataFrame()
comp_df['actual']=y_test
comp_df['pred']=y_test_pred
comp_df.head()

actual  pred
620       0     0
724       0     0
229       0     0
119       0     0
235       1     1

In [19]:
from sklearn.metrics import accuracy_score

In [20]:
print('Test Accuracy=',accuracy_score(y_test, y_test_pred))

Test Accuracy= 0.6926406926406926


In [21]:
y_train_pred=DTC.predict(x_train)  

In [22]:
y_train_pred

array([1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,

In [23]:
comp_data=pd.DataFrame()
comp_data['predict']=y_train_pred
comp_data['actual']=y
comp_data.head()

predict  actual
0        1       1
1        0       0
2        1       1
3        1       0
4        1       1

In [24]:
print('Train Accuracy=',accuracy_score(y_train, y_train_pred))

Train Accuracy= 1.0


In [25]:
DTC.feature_importances_

array([0.38074171, 0.09181314, 0.06747046, 0.04876617, 0.18754397,
       0.11170487, 0.11195969])

In [26]:
feat_imp=pd.DataFrame()
feat_imp['columns']=x.columns
feat_imp['values']=DTC.feature_importances_*100
feat_imp=feat_imp.sort_values('values',ascending=False)
feat_imp.head()

columns     values
0   glucose  38.074171
4       bmi  18.754397
6       age  11.195969
5  pedigree  11.170487
1        bp   9.181314

In [27]:
from sklearn.model_selection import GridSearchCV

In [28]:
param_grid={"criterion" :['gini','entropy'],
            "max_features" :[1,2,3,4,5],
            "splitter" :['best','random'],
            "min_samples_leaf" :[2,3],
            "max_depth" :[1,2,3,4,5,6,7,8,9,10]
           }

In [29]:
optimised_patient=GridSearchCV(DTC,param_grid,scoring='recall',cv=10)
optimised_patient=GridSearchCV(DTC,param_grid,scoring='accuracy',cv=10)

In [30]:
optimised_patient.fit(x_train,y_train)

/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=10, error_score='raise-deprecating',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'criterion': ['gini', 'entropy'], 'max_features': [1, 2, 3, 4, 5], 'splitter': ['best', 'random'], 'min_samples_leaf': [2, 3], 'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=0)

In [31]:
optimised_patient_data=optimised_patient.best_score_
optimised_patient_data

0.7579143389199255